### ISSUE TITLE
[BUG] Please Fix Structured Data Errors Showing in Google Webmaster Tools!

### ISSUE THREAD

**Issue by thelacesz** [presscustomizr/hueman#100]
Hello Alx!

Webmester tools error:
![snapshot18](https://cloud.githubusercontent.com/assets/842504/6635575/e35d64de-c967-11e4-8dc0-baa438dcb799.png)

Fix example:
https://www.acceleratormarketing.com/trench-report/google-analytics-errors-and-structured-data/

Please Fix it!

**Comment by andreaskas** [comment]
take a look here until we have a fix for this...
https://wordpress.org/support/topic/google-strutured-data-tool-errors?replies=1

**Comment by jaylinski** [comment]
+1
