### ISSUE TITLE
[BUG] Please fix this important bug for SEO

### ISSUE THREAD

**Issue by LeonardoCiaccio** [presscustomizr/hueman#101]
Prepend white space in to sitemap.xml by plugin, i have tested with some plugins for SEO but have white space before xml signature http://grabanymedia.altervista.org/sitemap_index.xml

![themabug](https://cloud.githubusercontent.com/assets/1698144/6645363/434dea7c-c9bc-11e4-908d-b57c8a9dfef0.PNG)

**Comment by elliot-labs** [comment]
Sitemaps are generated by your SEO/site map plugin. The theme does not create one.
