### ISSUE TITLE
More control of thumbnail sizes

### ISSUE THREAD

**Issue by RGunning** [presscustomizr/hueman#102]
image post requires images of certain dimensions, and photos are cropped to these dimensions.

Lots of photos I include are portrait, so get cropped when I want to display the full image in the image post type

Can you provide more control of image sizes. in different locations.

**Comment by elliot-labs** [comment]
Could you explain what you want in different words? I don't understand...

**Comment by RGunning** [comment]
The easiest is to show you with an example. http://rjg70.user.srcf.net/wordpress/test-post/

This is a image type post with a portrait image (375 × 500  http://rjg70.user.srcf.net/wordpress/wp-content/uploads/2015/04/91ef76c6a7efce1b0ffa07afae51f3deb58f6586.jpg) set as the featured image. By default the theme will choose the cropped version of the image (720 x 340  http://rjg70.user.srcf.net/wordpress/wp-content/uploads/2015/04/91ef76c6a7efce1b0ffa07afae51f3deb58f6586-720x340.jpg) 

As I'm using the image type post and it will appear at the top of the page, I would like the original image to display rather than the cropped one.

Whilst I can make this change in a child theme by modifying the inc/page-image.php, it would be a nice feature to have more control over the cropping and image inclusion by default

**Comment by elliot-labs** [comment]
Interesting... Thanks for the clarification!
