### ISSUE TITLE
Header Ad is not showing after Wordpress (4.1.2) update

### ISSUE THREAD

**Issue by gurjyot** [presscustomizr/hueman#104]
Before the update everything was good, but update happened automatically and just after the update the header ad stopped showing. 
Can this be fixed??

**Comment by brucedbrown** [comment]
Header Ads are working for me in theme v2.2.3 WP v4.2

**Comment by gurjyot** [comment]
I just checked that the theme is at v1.5.4 and I haven't got any updates information from Wordpress. 
Maybe because the theme never got updated at wordpress repository.
So I'll update the theme and then I'll report again.
But thanks for you time...:)

**Comment by brucedbrown** [comment]
It's also working on another site I'm running with theme v1.5.4 and WP v4.2

**Comment by jaylinski** [comment]
I also noticed that the theme does not update, even there should already be version 1.5.6 (with security fixes). please publish it on wordpress!

**Comment by robiin-hood** [comment]
The author doesn't have any control over the theme review process or when the updates are pushed to the theme repository.

**Comment by gurjyot** [comment]
I don't know what the issue is, but even after updating theme to latest version, the header ad is not showing.

**Comment by robiin-hood** [comment]
@gurjyot - how about posting the issue on the theme support forum and we can work on it there:
https://wordpress.org/support/theme/hueman#postform.

**Comment by jaylinski** [comment]
@robiin-hood didn't know that, thanks for the info!

**Comment by gurjyot** [comment]
Hello @robiin-hood, as per your suggestion I have added a question in WordPress forum as well.
