### ISSUE TITLE
HTML in copyright field (footer) after anti XSS patch

### ISSUE THREAD

**Issue by signaleleven** [presscustomizr/hueman#113]
Hey @AlxMedia!

After this commit https://github.com/AlxMedia/hueman/commit/fecd8d826c47e535fd400720caccc65ed765bf0e 
my footer looks funny. 

I had some HTML code in the custom copyright field, and of course now it's escaped. 
I easily reverted the change in my fork, but I am interested in what kind of XSS threat you expect there. I control what code I put in that field... "what could go wrong?" :) (I'm sure I'm missing something...)

Thanks!
Mike

**Comment by robbinhood** [comment]
Fixed in v3.0.11
