### ISSUE TITLE
Need add color transparent

### ISSUE THREAD

**Issue by VadymVolos** [presscustomizr/hueman#116]
Example:  background-color: rgba(5, 137, 222, 0.38);

**Comment by keunes** [comment]
Hi @VadymVolos,
Could you explain a bit more? Do you know the possibilities of child themes? Or if that's not suitable for your situation, please explain what exactly it is what you think would need.
That makes it easier for the developer & other to know what to do.

**Comment by VadymVolos** [comment]
The theme settings have the opportunity to choose the color.
I wish that there was a possibility to choose the transparent color.

Exaple:
#nav-topbar.nav-container {  background: rgba(38, 39, 43, 0.65); }
And for all the other blocks.
