### ISSUE TITLE
Need add change color for footer menu

### ISSUE THREAD

**Issue by VadymVolos** [presscustomizr/hueman#117]
Need add change color for footer menu

**Comment by keunes** [comment]
Hi @VadymVolos,
Could you explain a bit more? Do you know the possibilities of child themes? Or if that's not suitable for your situation, please explain what exactly it is what you think would need.

**Comment by VadymVolos** [comment]
The theme settings, you can choose a color for the header menu.
But there is no possibility to choose a color for the footer menu.

It is also desirable to be able to choose the text color buttons.
Also, choose the transparent color for background menu.

=
Example:
<style>
#footer { /* footer-ads del */ background: rgba(255, 255, 255, 0); }
#footer-ads { border-bottom: 1px solid #404143; }
#nav-footer.nav-container { border-top: 1px solid #404143; }
#nav-footer.nav-container, #footer-bottom #back-to-top { background: #26272B; }
#footer-bottom #back-to-top { background: #26272B; }
</style>
