### ISSUE TITLE
Need add textarea after tag <body> for code Google Tag Manager

### ISSUE THREAD

**Issue by VadymVolos** [presscustomizr/hueman#118]
Need add textarea after tag <body> for code Google Tag Manager

**Comment by keunes** [comment]
Hi @VadymVolos,
Could you explain a bit more?
Can't you add the Google Tag just [in a child theme via the functions.php file](https://wordpress.org/support/topic/adding-google-analytics-tracking-code-2#post-5693218)?
Or is this a feature request to add a field like there was a field for Google Analytics?

**Comment by VadymVolos** [comment]
1. The code after the <body> tag I can add only header.php
2. People are not able to edit the code. The theme settings in order that those who are not able to edit the code can be easily inserted.
