### ISSUE TITLE
WordPress.org Issue

### ISSUE THREAD

**Issue by elliot-labs** [presscustomizr/hueman#144]
The theme has not been updated on WordPress.org. Is this intentional or are you waiting for it to be approved?

Thanks!

**Comment by pablopaul** [comment]
Same question here

**Comment by Nikeo** [comment]
Hi, the last update on wp.org has been done 3 weeks ago ( see here : https://themes.trac.wordpress.org/ticket/28749#comment:7 )

The next update will be done during the month of January.

Cheers !
