### ISSUE TITLE
SVG Header Logo

### ISSUE THREAD

**Issue by elliot-labs** [presscustomizr/hueman#145]
It appears that SVGs are not supported as a logo in the header. They are supported as a header image and they work properly but I can't get them to work as a logo, I think it is displaying as one pixel as there is no "broken image" icon where the header logo should be.

Thank you for your awesome theme!

**Comment by achalpandeyy** [comment]
Does it work now?

**Comment by Dan-Danielson** [comment]
In my case, when sgv header image is used, the image is sometimes rendered smaller than it should and in some cases, the header overlaps with the webpage concent uder header. Tested with a few different svg files from different sources.

It still needs a bit of fine-tuning and testing. (On the other hand, svg in footer works like a charm, so I hope one day it will work it header, too).
