### ISSUE TITLE
Child theme activation shuffles widgets

### ISSUE THREAD

**Issue by pablopaul** [presscustomizr/hueman#152]
Helo, 

I started with hueman without a child theme and made some settings, especially moved a lot of widgets in different areas.

After a while I added a child theme and activated, this moved the existing widgets randomly to other sections.

Anybody else experienced that?

Thanks

**Comment by robbinhood** [comment]
Sidebars, widgets and menus are assigned specific IDs by the theme. If the new theme (your child theme) doesn't use the same ID the elements may move and/or be "lost", and you may need to adjust and/or recreate them.
