### ISSUE TITLE
Line numbering issue with SyntaxHighlighter Evolved

### ISSUE THREAD

**Issue by GeoHolz** [presscustomizr/hueman#157]
Hello,

Sometimes line numering doesn't works and stop before end of [/language]

See at https://blog.jolos.fr/2015/06/serveur-telechargement-jdownloader-2/

Alex Mills, the author of the plugins SyntaxHighlighter say that is it a theme issue ( https://wordpress.org/support/topic/line-numbering?replies=1 )

Can you help me ?

**Comment by Viper007Bond** [comment]
Well, theme "issue" more in that the theme and plugin just aren't playing nice together. It's not really either one's fault, although either is technically capable of fixing the problem.

I left some details in that support forum thread.

**Comment by GeoHolz** [comment]
Hello here,

There are update every week now.
Thanks for your job.

Can you look for my bug ?

Thanks
