### ISSUE TITLE
I would really love to see a sticky sidebar as part of your theme

### ISSUE THREAD

**Issue by Sawascwoolf** [presscustomizr/hueman#158]
Hi all,

I want to add a feature suggestion:
Make the sidebar sticky when it's last element is visible.

There should be a script inside wordpress to reuse since this functionality is implemented in the edit post screen. When writing long articles and scrolling down the sidebar will stay visible to the end of the page instead of disappearing.

As my Blog features long articles I've got the following choice to offer a side bar to the end of the page:
**make it longer** But this will decrease the usability for smartphone or tablet users and will increase the page load time (since more images will be loaded).

Please investigate if you could implement such a "sticky" sidebar, this will make your theme unique.

**Comment by pknadella** [comment]
will be a nice feature if implemented in the theme, but not necessarily ..... there are other plug-in's to achieve this, popular one among them is **Q2W3 Fixed Widget** (Sticky Widget)

**Comment by Sawascwoolf** [comment]
The Q2W3 Fixed Widget Plugin doesn't do what I want.
I don't want to have a single Widget fixed, but the whole sidebar to become fixed when the last widget is completely visible.

**Comment by pknadella** [comment]
ahh ok..... this Q2W3 plugin gives an option to make every widget fixed, so may be you can try enabling the fixed option for every widget in the sidebar, but this may have some responsive issues.

I don't think the makers of this theme will be addressing this issue, as your request is a very specific one and not a generic feature from which majority of users benefit.......... I guess you have to try doing this yourself from the scratch, I haven't tried it but the below link seems to be a legit solution to start working with [http://www.pixelbind.com/make-a-div-stick-when-you-scroll/](http://www.pixelbind.com/make-a-div-stick-when-you-scroll/).... If I get some time to implement this successfully then I will definitely post the solution here.... good luck

**Comment by robbinhood** [comment]
Here's another plugin you might try:
https://wordpress.org/plugins/sticky-menu-or-anything-on-scroll/

**Comment by Sawascwoolf** [comment]
Thank you for the suggestion, but this doesn't offer the behaviour I would love to have.
See this example at http://jsfiddle.net/LntUP/
There it is shown what I would like to have.
I think every user of the theme will love it although they currently don't know they want it.

**Comment by Nikeo** [comment]
Hi @Sawascwoolf , I like the last fiddle example.
And yes I agree this is useful. I don't think this is a "plugin territory", this totally make sens to include it in the theme.

I would tend to think that the default behaviour should be to stick to the top widget and have an option allowing users to stick the last one.

set as enhancement candidate.

**Comment by browsejobs** [comment]
Hi @Nikeo 
Make Side Bar Like this theme
http://themes.tielabs.com/demo.php?theme=sahifa
****************************
this theme side bar is perfect automatically adjust depend on post length
So user like this type of option
