### ISSUE TITLE
Add Schema (author or person & Aggregate Review & Blogpost )

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman#165]
initially reported here
https://wordpress.org/support/topic/the-new-hueman-needs-beta-testers?replies=13

Google Already announced schema play major role in future

**Comment by browsejobs** [comment]
thanks Nikeo
schema is very impoirtant
Today i Given two links from google partner sites
check once and Think about that 
--------------------------------------------------
Structured data is a way for publishers to highlight content on their web pages to help search engines know exactly what certain words relate to, such as product review scores or addresses. Schema.org is a shared markup vocabulary recognized by search engines to help with structured data efforts. Google provides a help section about structured data here. More information on structured data can also be found in our articles below.
source :  #http://searchengineland.com/library/search-engine-optimization/schema-dot-org
------------------------------------------------------------------------------------------------------
How many of using perfectly
http://searchengineland.com/schema-markup-shows-36-google-search-results-almost-websites-use-study-189707
--------------------------------------
Please add Schema to hueman theme ( plugins are not working properly)

 #Thirupa
[http://browsejobs.net/](url)

**Comment by Sh4d0wHunt3rX** [comment]
Hi :)
It seems the schema structured markup not works on your theme. When I enable the option, nothing adds in source code of posts. For now I have to use another plugin "schema app structured".

Do you confirm the issue?
