### ISSUE TITLE
Missing Featured Category Setting

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/hueman#167]
Hi,

As reported by user in this support thread.
https://wordpress.org/support/topic/missing-featured-category-setting?replies=2

This is no Featured Category setting in Appearance -> Customize -> Content -> Blog Design and Content

Thank you,
Denzel

**Comment by zecompadre** [comment]
tks @denzelchia

**Comment by Nikeo** [comment]
fixed in v3.0.9
