### ISSUE TITLE
Do not redefine customizer styles (colors etc)

### ISSUE THREAD

**Issue by slaFFik** [presscustomizr/hueman#168]
It's frustrating and doesn't look that good comparing to the default.

**Comment by Nikeo** [comment]
Hi @slaFFik 
can you elaborate a little bit more?
thanks

**Comment by slaFFik** [comment]
![image](https://cloud.githubusercontent.com/assets/282234/14486273/a04042d0-0164-11e6-8e87-35c3af5ecc9a.png)

**Comment by slaFFik** [comment]
And here are default styles (also not so wide options panel)
![image](https://cloud.githubusercontent.com/assets/282234/14486312/bf5ad9a0-0164-11e6-8406-c75b630ab926.png)

**Comment by Nikeo** [comment]
Ok.
Color choices are subjectives and can be discussed I agree.

But don't you think that the panel width adapts to the device is a good think ?

**Comment by slaFFik** [comment]
**Colors**
IMO - would be nice to inherit default style, so all themes have the same theme options management. Consider it like admin area for theme versus admin area for site. WordPress wp-admin is the same on all sites by default.

**Width**
But that means that a theme provides a different customizer experience comparing to WordPress core - which doesn't adapt. Also the difference between 15" and 23" is so small (<60px) and doesn't provide additional value (nothing changed in terms of customizer layout, readability not improved, management not made easier - it's just a bit wider with no real benefits), that I'm not sure that this subtle change is worth extra time for development and maintaining of this width-adaptation.

---

Of course, all the above is just my opinion as a theme user. You are absolutely free to ignore or not those requests. I just wanted to provide a feedback based on my use cases and usage experience.

**Comment by Nikeo** [comment]
I've actually think about your feedback and I found it relevant for the colors.
In the latest version, the customizer style is back to wp default for some elements.
