### ISSUE TITLE
Give ability to hide Help admin bar menu item

### ISSUE THREAD

**Issue by slaFFik** [presscustomizr/hueman#171]
![image](https://cloud.githubusercontent.com/assets/282234/14486481/d9674422-0165-11e6-84ac-e0db16c3356c.png)

Cases:
- site owner is a developer and don't need support (links)
- site developer wants to hide that link from a site owner, as he is providing support (paid or whatever)
- no ability to edit php files to hide this link via filters

**Comment by Nikeo** [comment]
Good point. Enhancement candidate
