### ISSUE TITLE
[Question/Request] Template change to group news by date

### ISSUE THREAD

**Issue by gntvls** [presscustomizr/hueman#179]
Hey, i have one strange question or request. Is it possible that you make an option in template configurator to select setting and make the content look similar to this one : 

![test](https://cloud.githubusercontent.com/assets/3038156/14553176/cb20078e-02e4-11e6-8f0e-d45c0367b761.jpg)

 I edited code myself and made posts grouped by day, but with every update it must be re-applied, this is not the way to . So yeah, i'm asking maybe there can be an option for "Basic posts display" like in my screenshot ?

Thanks!

**Comment by robbinhood** [comment]
> I edited code myself and made posts grouped by day, but with every update it must be re-applied

Did you modify the actual theme files? You should be using a child theme.

**Comment by gntvls** [comment]
Yeah i edited theme files to look if its possible  to do. Im new to wordpress so not sure what is child theme, i need to read some info about this

**Comment by robbinhood** [comment]
This location is really for tracking theme issues. If you can <a href="https://wordpress.org/support/theme/hueman#postform">start a new topic here</a> I'll be glad to help you. Thanks.

**Comment by keunes** [comment]
Just to check: feature requests should be posted in the WordPress system rather than here?

**Comment by robbinhood** [comment]
Your feature request was correctly posted here. In regards to opening a new topic I was referring to your statement about being new to WP and not sure what to do with a child theme. If you wanted help with that then a request for that should be posted in the support forum.

**Comment by gntvls** [comment]
Ok, sorry for that.

**Comment by robbinhood** [comment]
No apology needed. Glad to help any way we can.
