### ISSUE TITLE
Widgets :  change the date format to be more dynamic, or at least use the general date format specified in WP?

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman#183]

**Comment by robbinhood** [comment]
Widget date format was originally condensed to save space.

**Comment by akalkid** [comment]
because,  this notation differs from country to country.
Now it should continue modified whenever the theme upgrade.

I want next code.
the_time ( 'j M, Y') -> the_time (get_option ( 'date_format'));

**Comment by robbinhood** [comment]
Related to #83
