### ISSUE TITLE
Menu levels on mobile

### ISSUE THREAD

**Issue by gntvls** [presscustomizr/hueman#186]
Hey, i saw strange thing on mobile, if a menu has child menus, they are all expanded
https://www.dropbox.com/s/zbj742uko94gdmb/Screenshot_20160414-192839.png?dl=0 is this right?

![unspecified](https://cloud.githubusercontent.com/assets/3038156/14537570/d3842260-0277-11e6-87e0-baa9c385f1e0.png)

**Comment by robbinhood** [comment]
That's the default theme configuration.

**Comment by gntvls** [comment]
Ok understood. Maybe there will be an option in the future to switch between this and collapsed versions ?

**Comment by Nikeo** [comment]
Hi, 
thanks for reporting this. This is not a top priority for now in the enhancements and issue queues.
I set it as a potential enhancement for the future.

**Comment by gntvls** [comment]
Ok, thanks!
