### ISSUE TITLE
If I set "Featured Post Count" more than 1 it really bugs around. I had 6 and now set to 1

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman#187]
reported here
https://wordpress.org/support/topic/lost-all-march-articles?replies=3#post-8279274

Not able to replicate the issue yet.

**Comment by robbinhood** [comment]
Resolved by activating Featured Posts > Display the featured posts also in the list of posts.

**Comment by Nikeo** [comment]
ok.
I close this one then.
