### ISSUE TITLE
Add change log file to theme

### ISSUE THREAD

**Issue by robbinhood** [presscustomizr/hueman#189]
Or expand the Changelog section in About Hueman to scroll historical changes.

**Comment by Nikeo** [comment]
Good point.
in the "About Hueman" page, I keep track of the last changelog only for the moment.
I could include up to 5 releases for example.

Note that the full changelog is always available in the readme.txt file

**Comment by robbinhood** [comment]
Oh yeah, the "readme.txt" file. Never occurred to me to look there...;-) Not a big deal. Was just thinking users might be looking for the old chagelog.txt file.

**Comment by Nikeo** [comment]
I did not remember there was a changelog.txt file before.
there's a [on going discussion](https://make.wordpress.org/themes/2015/04/26/changelog-proposal/) about adding a changelog to themes, like plugins does, 
I'm not sure of the status of this discussion right now.
