### ISSUE TITLE
jquery.js?ver=1.12.3:2 Uncaught Error: Syntax error, unrecognized expression: a[href=#comments]

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman#197]
http://demo-hueman.presscustomizr.com/2013/10/27/taking-matters-in-your-own-hands-not-giving-your-power-away/#comments

**Comment by robbinhood** [comment]
See also: https://wordpress.org/support/topic/jquery-error-when-comment-id-in-url

**Comment by gntvls** [comment]
When we can expect a fix for this ? I took a fast look into this issue on: https://wordpress.org/support/topic/read-this-first-wordpress-45-master-list But didnt find how to solve it.

Thanks

**Comment by Nikeo** [comment]
This is fixed in the next release still in dev. Will be available in a few hours.

**Comment by gntvls** [comment]
Nice! Thanks!
