### ISSUE TITLE
Styles in Child Theme is not able to overwrite hueman-main-css ( wrong loading seqence )

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/hueman#199]
Hi,

With reference to this forum thread.
https://wordpress.org/support/topic/no-child-stylecss-with-version-3012?replies=9

Since update, I notice CSS codes has been moved in hueman-main-css
But the problem is parent theme as well as child theme style.css loads before hueman-main-css
Therefore, styles in child theme is not able to overwrite styles in hueman-main-css

hueman-main-css should load before style.css

Thank you,
Denzel

**Comment by Nikeo** [comment]
Yes I'm on it !

**Comment by denzelchia** [comment]
Thank you! :)

**Comment by dhm80** [comment]
I had the same problem. As a simple workaround I adjusted the way the parent theme css is loaded:

```php
// Load parent theme CSS
function my_css_files()
{
    wp_enqueue_style(
	'hueman',
        get_template_directory_uri() . '/style.css',
        ['hueman-main']
    );
}
add_action('wp_enqueue_scripts', 'my_css_files');
```

Note: I don't use the `@import` method in the child-theme `style.css`

Now the order is:
1. parent theme hueman-main-css 
2. parent theme style.css
2. child theme style.css

**Comment by dhm80** [comment]
Fixed already in v3.1.0, thanks a lot! :+1:

**Comment by Guilly2503** [comment]
Hello

I don't if this feature has been fixed on the 3.1.0 version but I'm having the sae issue.
I installed the Being Hueman and I put some customisation code on style.css. 
It worked fine on the first time,  but on the second time when I needed to edit or insert more code It stopped working.. Even if I delete all the custom code there it doesn't update the site.
The only way I found to wipe out the custom code I have put on the first time is to delete the child theme but as soon I install it again all the code comes back even with a blank css

**Comment by Nikeo** [comment]
Fixed in v3.1.0.
@Guilly2503 what is the status of your issue with the latest version ?

**Comment by Guilly2503** [comment]
Still the same . Just tested

**Comment by Nikeo** [comment]
Weird. The problem has been fixed for all other users who reported it. And it's fixed on my side of course too.
Is there any chance you have a plugin cache enabled ? If yes, can you please try to clean the cache or disable it ?

**Comment by Nikeo** [comment]
ah wait, you're install is based on the Being Human theme. That could be the problem then.

**Comment by Guilly2503** [comment]
Yes i'm using the being Hueman  because I couldn't find child theme to download 
Do you have the link ???

**Comment by Nikeo** [comment]
The previous child theme must be updated.
I would recommend to install and activate the [Childify Me](https://fr.wordpress.org/plugins/childify-me/) plugin => then open the customizer and you'll create your child theme in 2 clicks.

**Comment by Guilly2503** [comment]
Let me try it ... be back in a minute

**Comment by Guilly2503** [comment]
Unfortunately now it not working at all ... All the custom css done seems to be ignored

**Comment by Nikeo** [comment]
Ok.
Where are you writing your custom CSS in your child theme?
Can you provide an example of rule not working anymore ?
thanks

**Comment by Guilly2503** [comment]
Ok...
Appearance> Editor 

and the code is this 

.entry.excerpt p {
    text-align: justify;
	color: #000;
}

#header {
 background: url(http://xxxxxxxxxxxxx.com/wp-content/uploads/2016/04/space-background-e1460887598444.jpg);
 background-size: cover;
}

#page {
  padding-bottom: 3px;
   
}

**Comment by Nikeo** [comment]
Hi,
this looks good. Make sure the selected theme is the child theme's one when editing from Appearance > Editor.

Since this is not an issue, I close this on github.
Please follow up if needed in the Hueman theme's forum : https://wordpress.org/support/theme/hueman

thanks

**Comment by Guilly2503** [comment]
Hi Nikeo
Sorry but i think I have misunderstood... The child theme customization still not working . Why this is not a issue ???

Thanks

**Comment by Nikeo** [comment]
ah sorry for the misunderstanding.
The github issues are designed to collect the problems that need to be fixed in the Hueman theme.
In the latests versions of the Hueman theme, adding custom style to a child theme works fine and has been tested and approved by all users who initially reported the bug.

Your particular problem is more related to your child theme and the way you apply customizations to it.

That's why it's more relevant to post your request in the theme's forum : https://wordpress.org/support/theme/hueman

Thanks :)

**Comment by Guilly2503** [comment]
I'll have look on there

Thanks for your time

**Comment by Guilly2503** [comment]
Hi Nikeo 

Just to close the case I have found the thread talking about the problem I was having.
I didn't realise that you have released an official version of the child theme, but now everything works perfectly...
Great work Mate 

Kind Regards
