### ISSUE TITLE
.container-inner {min-width} breaks theme option

### ISSUE THREAD

**Issue by lizaguiar** [presscustomizr/hueman#202]
Stylesheet now (v. 3.1.0) has this style: .container-inner {min-width: 1380px}
But this breaks Global Settings -> General design options -> Website Max-width

I´ve set max-width to 1200px, but that min-width breaks the design. Had to set min-width to 0 in my child stylesheet to fix that.

Not sure this min-width will help anyone. Thanks!

**Comment by Nikeo** [comment]
Hi @lizaguiar this has not been modified in the v3.0* versions.
I'm not about the replicate this problem. When I set a custom max widht in the option, it is actually taken into account and the rule : `.container-inner {min-width: 1380px}` does not break this.

Can you please let me know what is the browser ( vendor + version) on which you observe this ?

Thanks
