### ISSUE TITLE
No show slider in static homepage

### ISSUE THREAD

**Issue by mehrdadam** [presscustomizr/hueman#205]
Hi Nikeo
I using the static homepage and i set FlexSlider to my static page using the following method :
I remove `is_home() &&` from featured.php and add `<?php get_template_part('parts/featured'); ?>` to child menu that i made.
After update, FlexSlider not displayed in my homepage static. I searched and found `is_home() &&` in below address:
functions folder > init-front.php > line 429 >
`if ( has_post_format( 'gallery' ) || ( is_home() && ! is_paged() && ( hu_get_option('featured-posts-count') != '0' ) ) )`
I tested and removed that and my Slider work correctly, And what to do with this ?
Thanks.

**Comment by robbinhood** [comment]
https://wordpress.org/support/topic/error-in-show-slider-in-static-homepage
