### ISSUE TITLE
AdSense Script Runs In Footer and Sidebar But Not Header

### ISSUE THREAD

**Issue by robbinhood** [presscustomizr/hueman#207]
AdSense script runs when placed in a footer widget, footer ads widget or sidebar widget, but doesn't run in the header ads widget.
https://wordpress.org/support/topic/header-ads-inactive

**Comment by robbinhood** [comment]
User indicates it was solved using CSS:
https://wordpress.org/support/topic/google-responsive-ads-in-header-doesnt-work

**Comment by Nikeo** [comment]
ok thanks for the update @robbinhood !
