### ISSUE TITLE
Are these buttons supposed to be unstyled?

### ISSUE THREAD

**Issue by mrdnomaid** [presscustomizr/hueman#209]
As you can see here, this is my site using the Hueman theme in Google Chrome:
![image](https://cloud.githubusercontent.com/assets/14424577/14589624/883c6bfa-04de-11e6-871e-91cdf079b880.png)  

And this is a friend's site, that is using GeneratePress theme, also in Google Chrome:
![image](https://cloud.githubusercontent.com/assets/14424577/14589630/bf0abcf4-04de-11e6-8c99-790bce9574a7.png)

Both of these are the Jetpack email subscription widget, both using the latest version of all themes/plugins

**Comment by Nikeo** [comment]
Thanks for reporting this.
I'll see what are the css rules needed to have a better integration of this plugin on front-end
