### ISSUE TITLE
Featured Post Slider Controls Overflow Content Container

### ISSUE THREAD

**Issue by robbinhood** [presscustomizr/hueman#221]
If Featured Posts is enabled, and Featured Post Count is > 1, slider < > prev/next controls overflow content container. If "Display a custom heading for your blog" is not enabled, and the Header menu is enabled, slider controls are partially hidden by the menu.
https://wordpress.org/support/topic/featured-posts-arrows-not-visible-without-custom-heading

**Comment by Nikeo** [comment]
fixed in dev
