### ISSUE TITLE
Add Option or Hook to Override Default Image Placeholder

### ISSUE THREAD

**Issue by robbinhood** [presscustomizr/hueman#222]
User requested a hook to be able to designate their own image to use in place of the theme default image placeholder.
https://wordpress.org/support/topic/default-thumbnail-when-there-isnt-one-should-have-a-filter

**Comment by Nikeo** [comment]
Yes.
Some filters have to be included in the theme. This is typically a good use case of the apply_filters() function

**Comment by Nikeo** [comment]
fixed in dev

**Comment by answerquest** [comment]
you fixed this? how? where? what can we do to change the default thumbnail?
