### ISSUE TITLE
Date format for localization

### ISSUE THREAD

**Issue by menakas** [presscustomizr/hueman#225]
Question on the site (disqus forums) from a customer:

Shouldn't end of line 17 in single-author-date.php say
the_modified_time(get_option('date_format'));
rather than:
the_modified_time('F j, Y');
for localization, etc.?

**Comment by Nikeo** [comment]
Yes. The problem is that it's been like that since the beginning to the theme and many users might see a different date format displayed if their date_format option is not 'F j, Y'

**Comment by dhm80** [comment]
@menakas I just came accross the same problem: It just doesn't look right with the different date formats.

@Nikeo Even if it was "wrong" since the beginning of the theme it's still a bug to me. So why not correct it?

**Comment by Nikeo** [comment]
@dhm80 I agree 100%. This will be fixed
