### ISSUE TITLE
Blank area still in the content part when social buttons are disabled

### ISSUE THREAD

**Issue by dbulbukas** [presscustomizr/hueman#226]
I have turned off the social buttons, but the area dedicated to them is still in the content part, just blank. Ir makes the content block inconsistent, with too large padding om the right.
![clipboard-1](https://cloud.githubusercontent.com/assets/18588158/14698472/cf3c6648-0797-11e6-8a5a-0a00088f7643.jpg)

**Comment by Nikeo** [comment]
duplicated : https://github.com/presscustomizr/hueman-addons/issues/6
related to hueman-addons

thanks for reporting
