### ISSUE TITLE
Social links - remove defaults

### ISSUE THREAD

**Issue by menakas** [presscustomizr/hueman#227]
From the customizer panel, Global Settings -> Socal Links, there is no option to remove the default G+ and Pinterest links from the share bar.

Also, please correct the typo for **without** in this section.
**Twitter Username (whithout "@")**

**Comment by Nikeo** [comment]
Hello Menaka, thanks for reporting the problem !

_Note : please report the plugin related issues in the relevant github repo => https://github.com/presscustomizr/hueman-addons/issues_
