### ISSUE TITLE
'dev' as default branch

### ISSUE THREAD

**Issue by keunes** [presscustomizr/hueman#228]
Shouldn't dev be the default branch for this repo (rather than master)? For almost all PR's the response is sth along the lines of 'Thanks! Added in dev' :P

Saves @Nikeo time if they could be merged into dev directly (I assume) and, IMHO more importantly, working that way acknowledges code contributors (now their work is copied and not included in the contributors graphs/statistics).

**Comment by Nikeo** [comment]
Yes, I'm moving toward this workflow, this was a transition period recently. Thanks for this feedback
