### ISSUE TITLE
Header Image alt is empty

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/hueman#230]
Hi,

With reference to this line of code.
https://github.com/presscustomizr/hueman/blob/dev/header.php#L58

The header image alt is empty because, it's missing echo.
Should be `echo get_bloginfo('name');` or `bloginfo('name');`

Thank you.

**Comment by Nikeo** [comment]
thanks for reporting Denzel !

**Comment by denzelchia** [comment]
You are welcome! :)
