### ISSUE TITLE
OptionTree: Header Logo Image Max-height does not update "live" (in Customize View)

### ISSUE THREAD

**Issue by fwolfst** [presscustomizr/hueman#231]
When in "Customize" view (FF 46, WP 4.5.1, fresh childified me Hueman 3.1.1 child theme, Addon installed), updating the "Header Logo Image Max-height"-value and pressing "save & publish" does not have an immediate effect (-> reload required). This does not pose a real problem, but should either be fixed or mentioned below the respective Option.

Thanks. Great stuff.

**Comment by Nikeo** [comment]
ok thanks for reporting

**Comment by Nikeo** [comment]
and you nice comment :)
