### ISSUE TITLE
Although sharing of posts is disabled, entry themeform div also has "share" class, inappropriate min-height

### ISSUE THREAD

**Issue by fwolfst** [presscustomizr/hueman#234]
Although I disabled single post sharebar, the respective div has the `share` class on it, enforcing a min-height of 354px, which creates a lot of white space in an examplary low-word video Post.

I dont really know php or wordpress, but I suggest the first pointer starts at single.php:20 :
`<div class="<?php echo implode( ' ', apply_filters( 'hu_single_entry_class', array('entry','themeform') ) ) ?>">`

**Comment by robbinhood** [comment]
Related to hueman-addons issues #5 and #6
