### ISSUE TITLE
Invalid HTML because of duplicate ids

### ISSUE THREAD

**Issue by dhm80** [presscustomizr/hueman#238]
Hey!

Unfortunately there are several invalid tags in the current Hueman theme (not good for SEO).

The biggest problem seem to be duplicate "id" attributes set in the code, especially with the social buttons:
https://validator.w3.org/nu/?doc=http%3A%2F%2Fdemo-hueman.presscustomizr.com

Cheers,
Ansas

**Comment by Nikeo** [comment]
thanks for reporting the problem !
Fixed in the next release
