### ISSUE TITLE
Single Post Author Link Formatting

### ISSUE THREAD

**Issue by robbinhood** [presscustomizr/hueman#239]
Link formatting is broken if post author profile Website option contains a value. (v3.1.2)

BY ADMIN" REL="AUTHOR">ADMIN · MAY 3, 2016

```
<span class="vcard author">
     <span class="fn"><a href="&lt;a href=" http:="" presscustomizr.com="" hueman="" "="" title="Visit admin’s website" rel="author external">admin</a>" rel="author"&gt;admin</span>
</span>

```
https://wordpress.org/support/topic/post-author-name-1

**Comment by Dee76** [comment]
Submitted Pull Request #240 to fix this issue.
