### ISSUE TITLE
Fix ot-loader php notices

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman#241]
Notice: Only variables should be passed by reference in hueman/option-tree/ot-loader.php on line 98

Notice: Only variables should be passed by reference in hueman/option-tree/ot-loader.php on line 326

**Comment by juniperpaul** [comment]
In my production site, these notices have disappeared upon upgrade to Hueman 3.2.8. (I'm using PHP 7.0.6 and WordPress 4.6.1.)
