### ISSUE TITLE
Share bar blocking view in mobile

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/hueman#242]
Hi,

As reported by user.
https://wordpress.org/support/topic/featured-posts-still-appearing-in-list-and-sticky-social-bar-in-mobile

The sticky share bar is blocking view on mobile.

This is a screenshot I took on my iPhone.
http://i.imgur.com/KkorYNn.png

Thank you
Denzel

**Comment by Nikeo** [comment]
Hi Denzel, thanks for reporting, I've mode this issue to the hueman plugin repo. https://github.com/presscustomizr/hueman-addons/issues/11
