### ISSUE TITLE
Add Options to Display/Hide Post Author and Dates

### ISSUE THREAD

**Issue by robbinhood** [presscustomizr/hueman#244]
Requested here: https://wordpress.org/support/topic/showhide-dates

And here for author/category/dates : https://wordpress.org/support/topic/blog-page-turn-off-author-category-date/

**Comment by ilee1990** [comment]
I really hope this enhancement happens soon. I need to remove the updated on date from my posts and i don't write code. I would rather not have to disable the structured data markup.

**Comment by giorgioriccardi** [comment]
While the team is working on it you could use some css rules to hide them. In the forum it has been already addressed in the past.
