### ISSUE TITLE
Use get_option date_format for all dates.

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/hueman#247]
Hi,

Not sure if this can be an enhancement request or this is a bug.
With reference to this thread. https://wordpress.org/support/topic/post-author-name-1?replies=26

Users are saying we should be using `get_option('date_format')` for all "visible" dates.
So that it reflects the setting in WordPress admin -> General -> Date format.

For example.

Since we are using `get_option('date_format')` for the Published Time.
https://github.com/presscustomizr/hueman/blob/dev/parts/single-author-date.php#L16

We should be using `get_option('date_format')` for the Updated Time too.
https://github.com/presscustomizr/hueman/blob/dev/parts/single-author-date.php#L17
As in the function `<?php the_modified_time('F j, Y'); ?>` we should be using `<?php the_modified_time(get_option('date_format')); ?>`

The same changes should also be applied to the time and date formats in 
https://github.com/presscustomizr/hueman/blob/dev/parts/post-list-author-date.php

Thank you.

**Comment by zecompadre** [comment]
Tks @denzelchia :) +1

**Comment by Nikeo** [comment]
fixed in dev
