### ISSUE TITLE
Header Advertisement Widget Not Displayed in Customizer Preview

### ISSUE THREAD

**Issue by robbinhood** [presscustomizr/hueman#265]
Even if the widget has content it is not displayed in the Preview. The Footer Full Width Widget displays properly in the Preview.

**Comment by robbinhood** [comment]
Well, there you go; I never noticed that arrow. Thanks for the update!

**Comment by eri-trabiccolo** [comment]
;)
That arrow is part of the wordpress code btw, no merits ;)
