### ISSUE TITLE
Skype protocol

### ISSUE THREAD

**Issue by Doxtra** [presscustomizr/hueman#268]
Hi, I believe Skype protocol `skype://` is not recognized in the social icon section.

**Comment by Nikeo** [comment]
Hi,

The theme uses `esc_url `to validate the url type data fetched from the database. This function, among other things, checks if the url protocol is allowed by WP.

I won't modifiy this list of allowed protocols in the theme. However, you can extend the list of WP allowed protocols using this documentation provided here : https://developer.wordpress.org/reference/functions/wp_allowed_protocols/

Cheers,

**Comment by Doxtra** [comment]
Thanks Nicolas. I will create a ticket and paste the code on
https://wordpress.org/support/theme/hueman for anyone interested.

Kind regards,
Christophe



2016-06-03 7:54 GMT+02:00 Nicolas Guillaume (@nikeo on wp.org) <
notifications@github.com>:
