### ISSUE TITLE
Add Default Language Files

### ISSUE THREAD

**Issue by robbinhood** [presscustomizr/hueman#270]
Add default language files to theme distribution so user can do translation.
https://wordpress.org/support/topic/translate-theme-to-dutch

**Comment by keunes** [comment]
Is that the right approach, I'm wondering? Maybe we can start collaborative translation by using Transifex (free for open source projects).

Just thinking that it's waste of space to add original language files to the standard installation.

**Comment by jaylinski** [comment]
translation should be done here: https://translate.wordpress.org/projects/wp-themes/hueman
