### ISSUE TITLE
replace post loop counter with core variable

### ISSUE THREAD

**Issue by chrismccoy** [presscustomizr/hueman#274]
i see we have

```
<?php if($i % 2 == 0) { echo '</div><div class="post-row">'; } $i++; endwhile; echo '</div>'; ?>
```

can be swapped with the wp query current post variable, to eliminate the not needed counter

```
<?php if($wp_query->current_post % 2 == 0) { echo '</div><div class="post-row">'; } endwhile; echo '</div>';?>
```

**Comment by Nikeo** [comment]
yep that's right.
candidate for v3.1.7
thanks

**Comment by chrismccoy** [comment]
any chance of adding this? its at 3.2.9 now, was suppose to be added in 3.1.7

**Comment by Nikeo** [comment]
set to v3.2.10 milestone
