### ISSUE TITLE
PHP 7.0 Compatibility: Extension 'mysql_' is deprecated and INI directive 'safe_mode' is deprecated

### ISSUE THREAD

**Issue by AngelGL** [presscustomizr/hueman#278]
According to the **PHP Compatibility Checker plugin**, the Hueman theme is not fully PHP7  compatible because:
## FOUND 2 ERRORS AFFECTING 2 LINES

 307 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and deprecated since PHP 5.6 and removed since PHP 7.0 - use mysqli instead.

**Comment by robbinhood** [comment]
Also reported here: https://wordpress.org/support/topic/php-error-class-admin-pagephp

**Comment by Nikeo** [comment]
Yep, thanks for reporting.
