### ISSUE TITLE
Menu needs some work (suggestions)

### ISSUE THREAD

**Issue by Nate82** [presscustomizr/hueman#284]
**1.** Setting mobile menu break points should be customized through options or at least easier to do in CSS. Currently you can't override the break points in child-theme css. So if you have a good bit of menu items it looks pretty bad on an iPad at 768px and pretty tight at 1024px.

![Image of 768px](https://s10.postimg.io/z8m7ap73d/768px.png)

**2.** Sub-menus are automatically expanded on mobile menu, this is :(
![Image of child menu](https://s16.postimg.io/sqq2gmw1h/childmenu.png)

**Comment by Nikeo** [comment]
Those are good points, and yes there's room for improvement I agree.

Which break points would you suggest ?

About pre-expanded mobile menu, this would require some research but yes I want to change this too.

**Comment by Nate82** [comment]
If possible, put an option in the theme admin customizer for the user to set their own break point, I've seen many themes do that and it's very convenient. If not possible then probably break it at 768px or allow it be overridden in child-theme CSS.
