### ISSUE TITLE
WP Posts Carousel plugin conflict with Img Smart Load

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman#289]
As reported by a user

> Just updated the theme on the website of my tennisclub (http://www.balletuin.nl). At the bottom I use the WP Posts Carousel plugin/widget. When I enable the "smart image load" option the images won't load. That is: it starts with a blank row, then the first 5 featured images come up, folowed by blanco "placeholders". When I disable the option the carousel works without any problem.

**Comment by ghost** [comment]
Not needed for v3.3.13
good candidate for v3.3.14
cheers
