### ISSUE TITLE
Customizer Footer Hides Bottom of Options

### ISSUE THREAD

**Issue by robbinhood** [presscustomizr/hueman#291]
The footer of the customizer which contains the view options is hiding the bottom of the options content.

![image](https://cloud.githubusercontent.com/assets/11847066/18234204/49eff560-72b1-11e6-90ab-c1c3f9a422fc.png)

**Comment by robbinhood** [comment]
Appears to be fixed in v3.2.4.

**Comment by Nikeo** [comment]
yes
