### ISSUE TITLE
WP embed not displayed correctly

### ISSUE THREAD

**Issue by mheiduk** [presscustomizr/hueman#298]
Hi,

it seems that the wp embed feature is not displayed correctly. I've tested it on my local machine with the newest Hueman version 3.2.0 without any modifications or a child theme. I tried to fix the problem, at the moment without success. The wp embed frame get cropped:

![image](https://cloud.githubusercontent.com/assets/291541/18343235/ce4e5500-75b2-11e6-98ae-3f29da1fe722.png)

On mobile you can't read the title anymore:
![image](https://cloud.githubusercontent.com/assets/291541/18343258/e4e7010e-75b2-11e6-88df-863fa1113890.png)

Maybe you can have a look at it? I'll try it too to fix the displaying issue.

Thanks!

Best,
Marc

**Comment by mheiduk** [comment]
Wp embed gets wrapped into .video-container, without it works nearly fine. To make it responsive set the iframe to max-width: 100%, thats what theme twentysixteen does.

I've found the function in functions/init-core.php, hu_embed_html() should exclude the wp embed functionality.

Best,
Marc

**Comment by Nikeo** [comment]
ok @mheiduk.
You've pointed an issue and provide the solution. Really cool !
I'm trying to fix this in the next release

**Comment by Nikeo** [comment]
fixed
