### ISSUE TITLE
Add image dimensions into header image customization

### ISSUE THREAD

**Issue by Tarun80** [presscustomizr/hueman#300]
I'm proposing a minor addition to the header-main file. This would allow setting the image height and width to allow for pages to better pass Google Pagespeed tests.

Currently I have to manually edit them in to header-main.php - line 24:
`<img class="site-image" src="<?php echo hu_get_img_src_from_option('header-image'); ?>" alt="<?php echo get_bloginfo('name'); ?>" width="200" height="64">`

If it would be possible to do this through customizing the theme that would be fantastic.

Additionally, if you have the generic thumbnail for posts, image dimensions are also not shown and do appear as issues when you try to check against Google Pagespeed.

**Comment by Nikeo** [comment]
Thanks for the suggestion @Tarun80 
Yes, the idea would be to get those dimensions from the wp attachment data and write them in the template.

**Comment by Nikeo** [comment]
example in the customizr theme
https://github.com/presscustomizr/customizr/blob/master/inc/parts/class-header-header_main.php#L201

**Comment by Tarun80** [comment]
@Nikeo unfortunately that link does not work, returns a 404.

**Comment by eri-trabiccolo** [comment]
@Tarun80 
You're right,  that link worked till one week ago, when all the parts files (and many others) have been merged in one file.
Anyway, here you can find the piece of code Nicolas was referring to.
https://github.com/presscustomizr/customizr/blob/v3.4.19/inc/parts/class-header-header_main.php#L222

**Comment by Tarun80** [comment]
Thank you for that, @eri-trabiccolo

**Comment by Tarun80** [comment]
Any word on this?

**Comment by ghost** [comment]
Hi @Tarun80, with the current version of the theme, the header image is rendered with 
 a pluggable function : hu_render_header_image() located here : https://github.com/presscustomizr/hueman/blob/dev/functions/init-front.php#L308

**Comment by ghost** [comment]
And that you can override in a child theme to add the dimensions attributes if needed.
Hope it helps

**Comment by Tarun80** [comment]
Is there no way you can add something to automatically detect and insert the image dimensions so that the theme passes validators?
