### ISSUE TITLE
Child theme for alx-tabs.php override not recognized

### ISSUE THREAD

**Issue by Tarun80** [presscustomizr/hueman#303]
Been testing this for the past hour. Tested on a dev install locally as well. Same issue.

I've been trying to customize the time/date display in the Hueman sidebar widget. Until 3.2.2 it worked fine. 

I've changed `the_time('j M, Y')` to `the_time('F j, Y')`. This is placed in `/hueman-child/functions/widgets/`

**Comment by robbinhood** [comment]
@Tarun80 - Please open a topic in the theme support forum so we can help you with this:
https://wordpress.org/support/theme/hueman

**Comment by Tarun80** [comment]
The thing is, I believe this is a bug since the file has to be manually edited and the settings are not being pulled from Wordpress itself for the date.

Under Settings > General I have it set to use F j, Y. The Hueman theme has it set via hardcoding to j M, Y. Settings should either pull from Wordpress or be able to be customized through theme settings. Don't you agree?

**Comment by robbinhood** [comment]
>Settings should either pull from Wordpress or be able to be customized through theme settings

Well, perhaps, but that's not a bug. It's coded that way because of space considerations.

**Comment by Tarun80** [comment]
Sorry, I meant that the settings aren't being pulled from the child theme edit as the bug.

**Comment by Tarun80** [comment]
Any word on this? It's still not honoring changes made to the child theme.
