### ISSUE TITLE
Theme Upgrade Doesn't Recognize Hueman Addons State

### ISSUE THREAD

**Issue by robbinhood** [presscustomizr/hueman#304]
When upgrading the theme with Hueman Addons plugin installed, a message is displayed saying plugin is inactive even when it is active. Clicking "Activate Hueman Addons" displays "Install Required Plugins" and shows Hueman Addons. Clicking "activate" returns "No plugins to install, update or activate."

**Comment by Nikeo** [comment]
Hi @robbinhood, thanks for reporting.
Do you still see the admin notification afterwards ?

**Comment by robbinhood** [comment]
I just ran an update from v3.2.3 to v3.2.4 and didn't have any problems. Not sure what happened previously. I think you can close this for now. Thanks.
