### ISSUE TITLE
Ext link plugin compat issue

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman#305]
external links"... BUT! in some plugins it is inappropriate!
such as: 1. WP-Appbox 2. Shortcodes-ultimate

**Comment by eri-trabiccolo** [comment]
In Customizr we handle this case by case. We might want to create a new option with excluded selectors, but this implies users know the selector. Otherwise...

**Comment by ghost** [comment]
yep.
not urgent anyway
have a good flight

**Comment by eri-trabiccolo** [comment]
Yeah, thanks. In Naples looking for a bus :(
Italy...the most organized state in the world!
