### ISSUE TITLE
Comments avatar size issue

### ISSUE THREAD

**Issue by gntvls** [presscustomizr/hueman#309]
Hello,
after every update i get comments like this: https://gyazo.com/2ce238166357f8edbe2d10e6a976440e

So i have to go to theme, comments.php and update line: 
`<?php wp_list_comments( 'avatar_size=96&type=comment' ); ?>`
To
`<?php wp_list_comments( 'avatar_size=48&type=comment' ); ?>`

Is this issue on my side or what ? 

Thanks.

**Comment by Nikeo** [comment]
Hi,
Thanks for reporting the problem. This avatar size will be fixed in the next update.

But you should not have had this problem, because the following css rule main.css should normally style this the right way

`
.commentlist .avatar {
    position: absolute;
    left: -60px;
    top: 0;
    width: 48px;
    height: 48px;
    -webkit-border-radius: 3px;
    border-radius: 3px;
}
`

**Comment by gntvls** [comment]
Thanks for update, but i still see some strange things
http://i.imgur.com/xcei4kN.png
http://i.imgur.com/rk55tr6.png

I think is only applies when custom avatar is added, and only for the post author.

**Comment by Nikeo** [comment]
What is a custom avatar ?

**Comment by gntvls** [comment]
That might be an avatar from lets say Facebook, when people login through it.
https://gyazo.com/00a70abdfb4cdad9635d1848c3b75d1e
Is it possible that this issue comes from Super Socializer plugin ?
Because custom avatars comes from their inputs

**Comment by Nikeo** [comment]
ok.
Yes it might be due to the plugin. Can you quickly disable it and let me know ?
Thanks

**Comment by gntvls** [comment]
Yes absolutely it is plugin fault. I disabled it and avatar came back to default grey "Unknown" from gravatar. 
I'm sorry for disturbing you. Now i must find solution on this issue :)

**Comment by Nikeo** [comment]
OK. No pb. You've pointed out an issue in the code so that was useful for both of us !

**Comment by gntvls** [comment]
OK, very good then!
