### ISSUE TITLE
comment-reply.min.js loading on pages with comments turned off

### ISSUE THREAD

**Issue by Nate82** [presscustomizr/hueman#312]
I have comments turn off for Pages but comment-reply.min.js still loads.

**In /hueman/functions/init-front.php where it loads:**

```
if ( is_singular() && get_option( 'thread_comments' ) ) {
      wp_enqueue_script( 'comment-reply' );
    }
```

**This should be changed to:**

```
if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
      wp_enqueue_script( 'comment-reply' );
    }
```

**Comment by Nikeo** [comment]
yep I totally agree. thanks @Nate82 !
will be fixed in the next update.
