### ISSUE TITLE
h1 absent if header image is used

### ISSUE THREAD

**Issue by ghost** [presscustomizr/hueman#314]
Hi,

h1 absent if header image is used, I discovered that, by going there
[seositecheckup](http://seositecheckup.com/)
who give me a problem on my site, no H1 
suddenly I looked, the h1 tag appears in the "Header Logo" but is empty  :
"I tried on a site with logo and Hueman
is the message
Your page Does not contenir Any H1 headings. H1 headings help indicate indication the major topics of your page to search engines. While less significant than Good titles and meta descriptions, headings H1 May still help define the topic of your page to search"

Without vital, as the titles of the posts in homepage are h2, that is a problem, the hierarchy of Hn is not respected, it must begin with H1
so I found the solution, I modified the file "parts/page title.php"
Line 4:  `<h2><?php echo hu_blog_title(); ?></h2>`
in
`<h1><?php echo hu_blog_title(); ?></h1>`

I redid a check on [](http://seositecheckup.com/)
I have an H1, but I told myself and articles, I have one H1, so I put the url of a post and yes, one not two H1 H1.
and I respect this post https://yoast.com/blog-headings-structure/
Maybe he should put H1 default for everyone in "page-title.php"?
Thank You

**Comment by robbinhood** [comment]
@noaneo - You might take a look at the discussion here:
https://wordpress.org/support/topic/no-h1-for-the-site-title/

**Comment by noaneo** [comment]
hi,
Thank you I found this discussion before asking the question.
The reply of the author of the theme is incorrect, it takes an H1 per page, when using banner instead of logo, in homepage, no h1.
