### ISSUE TITLE
W3 Validator errors when "Load images on scroll" turned on

### ISSUE THREAD

**Issue by Nate82** [presscustomizr/hueman#316]
Not sure if it's a big deal but it throws an error for each image on a page:
The sizes attribute may be specified only if the srcset attribute is also present.

https://validator.w3.org/nu/?showsource=yes&doc=http%3A%2F%2Fdemo-hueman.presscustomizr.com%2F

**Comment by Nikeo** [comment]
Thanks for reporting.
@eri-trabiccolo, do you have any idea for a possible fix ? thanks

**Comment by eri-trabiccolo** [comment]
Well yeah, where we replace the srcset with data-srcset in PHP we can do the same with the size attribuite and then revert it in the smartload js.
Should be fine.
rock&roll men! 😀
