### ISSUE TITLE
The long empty basement

### ISSUE THREAD

**Issue by marcusk9n** [presscustomizr/hueman#318]
Hello. It often happens that the basement in the sky.
Here's an example: http://prnt.sc/cnmw19
Website: my-cccp.ru

**Comment by Nikeo** [comment]
Hi @marcusk9n did you try to disabe your plugins to see if it fixes the problem ?

**Comment by marcusk9n** [comment]
No. Disable plug-ins have not tried.
But in previous versions it was not (with the same set of plugins).
