### ISSUE TITLE
RTL Support - 75% done need help for the rest

### ISSUE THREAD

**Issue by Gendows** [presscustomizr/hueman#320]
Hi,

i have modified some css and sidebar phps files to make the theme look like it supports RTL order

i started with an idea

> about the sidebars, just an idea
> what about changing the s1 and s2 width then i can put the widgets i want anywhere
> ## just need to make some changeable options for sidebar header, i can chose social links or custom text and another option for which sidebar should hide first on small screens 
> 
> i have the following questions – [My Website](http://gendows.com/)
1. slider arrows – the arrows are ok, but the function is reversed. how to fix?
2. i did the work on my laptop, so i didn’t notice about the small screens tell i ended 🙁 – anyway, the sidebars content collapse on small screens but keeping the width of 340 and 260, how to fix that?
3. can i reverse the order of closing sidebars? make s1 close before s2?
4. the social links on sidebar – the tooltip is hidden under the menu – how to fix that?
5. the next – prev post arrows, i tried to reverse them but font-awesome css override my css from the child theme – how to fix that?

if there is anything i haven’t configured yet, please let me know 🙂
there is an test admin account, if you want, just give me the email to see what i did

thank you in advance

**Comment by Gendows** [comment]
i fixed No. 2
But the social icons and 'More' text go a row down on small screens, the social icons color is invisible on the background. even in the main demo

**Comment by Nikeo** [comment]
Thanks for this analysis. I'm gonna investigate those points.
