### ISSUE TITLE
BUG: Comments section in customizer ignores per page comments options

### ISSUE THREAD

**Issue by slaFFik** [presscustomizr/hueman#321]
I need to enable comments for certain pages, and disable for others.
If I go to customizer and enable comments - it will work for all pages, no matter what settings I selected for individual pages.

**Comment by robbinhood** [comment]
This is working in v3.2.8. If the Customize > Global Settings > Comments > Pages Comments is enabled, checking/unchecking the individual page "Discussion - Allow comments" will display/hide the Leave A Reply section on the page.

**Comment by slaFFik** [comment]
Leave a reply - yes, but what about old comments that were left when the feature was on?
Would be nice to have ability to hide them.

**Comment by Nikeo** [comment]
Hi @slaFFik the hueman addons plugin will be updated soon with a new feature allowing you to "scope" each option for a given context. For example a single page. This should solve your problem.

**Comment by slaFFik** [comment]
@Nikeo oh, I didn't know about the existence of this plugin. 
Thanks!
