### ISSUE TITLE
How can i add new google fonts

### ISSUE THREAD

**Issue by salkii** [presscustomizr/hueman#330]
Hello, i use this theme for arabic blog and i want to add new arabic fonts from google to this theme but i can't do that.
I using the child theme 

I try to load custom font by this code in function.php

function arabic_hueman_scripts() {

wp_enqueue_style( 'hueman-style', get_template_directory_uri() . '/style.css' );

    if ( is_rtl() ) {
		wp_register_style('kufi-font', 'http://fonts.googleapis.com/earlyaccess/droidarabickufi.css');
	}
}
add_action( 'wp_enqueue_scripts', 'arabic_hueman_scripts' );

But this not working when i use font family is not working.
Any one can help me?

**Comment by robbinhood** [comment]
Hi salkii. This is the place to report theme problems or recommendations for enhancements to the development team. If you need help with issues on your site please start a new topic here: https://wordpress.org/support/theme/hueman#new-post. Thank you.
