### ISSUE TITLE
implement post view counter as a meta

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman#333]

**Comment by eri-trabiccolo** [comment]
Do you mean as custom post meta?

**Comment by Nikeo** [comment]
yes a simple custom post meta that would be incremented each time the post is displayed on front end.
Should be pretty easy to implement.

**Comment by Nikeo** [comment]
Because right now the theme includes a "popular" post widgets based on the comments count. Which is not the only criteria of popularity of course.

**Comment by eri-trabiccolo** [comment]
Ah I see, because it relies on an info WordPress has by itself, which is not true for the views count.
Maybe in the addon would be better, isn't it?

**Comment by Nikeo** [comment]
yep hueman ad. candidate

**Comment by Pharizna** [comment]
And in Hueman Pro, of course :

**Comment by hosseinfarnia** [comment]
Hi, @Nikeo 
Any plan to add this feature?
you can also use [this plugin](https://wordpress.org/plugins/wp-postviews/) to implement it which is very easy.
for example you can add the view icon next to the comment count icon in posts and pages.
