### ISSUE TITLE
php7 compatibility

### ISSUE THREAD

**Issue by dgirona** [presscustomizr/hueman#335]
This theme cause errors on php7 execution : (

**Comment by Nikeo** [comment]
Hi @dgirona can you paste the error(s) you get in your next reply ?
We're on it. This will be pushed in the next days.
Thanks

**Comment by dgirona** [comment]
In the last versión of the theme.

FILE: /www/wp-content/themes/hueman/functions/admin/class-admin-page.php
----------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AND 1 WARNING AFFECTING 2 LINES
----------------------------------------------------------------------------------------------------------------
 307 | ERROR   | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 315 | WARNING | INI directive 'safe_mode' is deprecated from PHP 5.3 and forbidden from PHP 5.4.
----------------------------------------------------------------------------------------------------------------
FILE: /www/wp-content/themes/hueman/functions.php
---------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------
 30 | ERROR | The use of function split is discouraged from PHP version 5.3 and forbidden from PHP version 7.0; use preg_split instead
---------------------------------------------------------------------------------------------------------------------

**Comment by Nikeo** [comment]
@dgirona 
There's no split() function in hueman/functions.php, line 30.
Is it something that you've added ?

**Comment by dgirona** [comment]
Changed widt explode(). Now all works fine. Thanks Nikeo : )

**Comment by Nikeo** [comment]
ok. Thanks for the feedback.
the fix will be merged in v3.2.10
