### ISSUE TITLE
Tabs Widgets : add CPT ?

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman#336]
As reported

> I really love the theme but there's one thing I'm really missing: I'd like to have the ability to add custom post types to the recent/popular posts tabs of the Alx Tab widget, so that I can choose myself which post types to display (posts, customs post types or a combination of both). Is there a change this will be included in future?

**Comment by fwolfst** [comment]
There is a couple of other additions that would ease CPT (Custom Post Type) integration, e.g. filter for same post type in the "related" section ("You may also like ..."), adding titles to (Custom Post Type-) archive pages and probably some more.
@Nikeo Would you'd be happy about PRs regarding improved CPT integration? Would you like to see separate issues for these?

**Comment by fwolfst** [comment]
Showing CPT Archive Titles in title-bar is sketched in this commit: https://github.com/ecovillage/hueman-7l-child/commit/fd991d1bee530eab9a840e42cb9aa1a2947daa58 .
I'd be glad to create a issue, branch and pull request, if you like.

**Comment by fwolfst** [comment]
I understand the issue triage, but would also have appreciated a comment. Just feedback.

**Comment by ghost** [comment]
I just created a new issue about this : https://github.com/presscustomizr/hueman/issues/838
The idea would be to use filter to alter the post queries, like already implemented for the Hueman Posts widget
