### ISSUE TITLE
User cannot create page due to PHP warning

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/hueman#338]
Hi,

Please refer to this topic on WordPress.org forum.
https://wordpress.org/support/topic/warning-message-in-header-cant-customize-site-anymmore/

Two users reported having problem creating page and seeing the following PHP warning message.

Warning: Creating default object from empty value in […]\themes\hueman\functions\czr\class-czr-init.php on line 323

I am not able to replicate this issue on my test site, but since there is already two user with similar issue, I guess I should make a report.

Please kindly help to investigate this error.

Thank you :)

Best Regards,
Denzel

**Comment by Nikeo** [comment]
Fix on the way thanks for reporting

**Comment by denzelchia** [comment]
Hi Nicolas,

You are welcome!
Thank you :) 

Best Regards,
Denzel
