### ISSUE TITLE
[customizer] : always check the existence of controls and settings instances before altering them

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman#340]
typically in functions/czr/class-czr-init.php#220, hu_alter_wp_customizer_settings()

related forum thread : https://wordpress.org/support/topic/warning-message-in-header-cant-customize-site-anymmore/#post-8408777

**Comment by denzelchia** [comment]
Hi Nicolas,

Another user reporting PHP warnings.
https://wordpress.org/support/topic/warning-creating-default-object-from-empty-value-34/

The lines are within function hu_alter_wp_customizer_settings()
Therefore I think it's related to this issue, so I posted it here.

Thank you
Denzel

**Comment by Nikeo** [comment]
yes looks related

**Comment by denzelchia** [comment]
Hi Nicolas,

Thank you for your reply.

I will reply to user on Hueman forum and let user know about this.

Thank you
