### ISSUE TITLE
Unable to go back when accessing General Design Options

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/hueman#345]
Hi Nicolas,

Please refer to this forum thread.
https://wordpress.org/support/topic/customiser-little-js-problem/

When accessing Appearance -> Customize -> Global Settings -> General Design Options.
The “back arrow” does not response when clicked.

I am using Hueman 3.2.10 with only Hueman Addons plugin.

Thank you

Best Regards,
Denzel

**Comment by Nikeo** [comment]
> Uncaught Error: prepareitemForAPI : a item must be an object to be instantiated.

**Comment by luvrockz** [comment]
same issue

**Comment by panitaxx** [comment]
I have the same issue. The console reports: 

Uncaught Error: Visibilities : a dominus control id is not registered : show_on_front

**Comment by Nikeo** [comment]
fixed in 3.2.11
