### ISSUE TITLE
[feature request] Sidebars : allow swapping positions of s1 and s2

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman#347]
Of course we can switch the widgets. But, you know both sidebars are not of the same width - s1 is wider than the s2.
I wanted to have the s1 (the wider one) moving next to the 'content' are and the narrower s2 moving all the way the right - Swapping the position of the two sidebars.
I believe this feature will greatly enhance the usability of this already great theme. Please look into it.

Another point for your review:

I stumbled upon a great plugin, "Post in Sidebars" - One of the very best, useful, and feature rich plugin. The author (Aldolat) is at the top when it comes to providing support to users. I thought it my be beneficial to both of you if you contact him and see if there is way for mutual help and support.

Thank you very much for giving us such great themes (with due credit to Alex Agnarson as well).

**Comment by keunes** [comment]
Related to #346

**Comment by fwolfst** [comment]
I'd like to see that, too. But I think this issue can be be closed in favor of https://github.com/presscustomizr/hueman/issues/411 , which is about general size adjustments to the sidebar(s). Although for me it would be enough if I'd can swap s1 and s2.

**Comment by mirenbz** [comment]
They may not be related (I mean sidebar _side_ and size). In our case, we use a 1 sidebar layout for our front-page (primary to the right), and then a 2 sidebar layout for the rest of the pages (which shows primary to the left and secondary to the right). I think this makes it really confusing. Is it possible to swap sidebars for the 2 sidebar layout (leave primary always to the right, secondary to the left), using a child theme?
