### ISSUE TITLE
Enhance favicon and path support

### ISSUE THREAD

**Issue by Tarun80** [presscustomizr/hueman#348]
When I was looking into the favicon feature on a dev version of my website, I tried a few things out.

If at all possible, in an upcoming release can we have the ability to apply custom names/rel and paths/hrefs to favicons please?

I ask because I noticed things like this:
```html
<link rel="icon" href="https://example.com/wp-content/uploads/favicon-150x150.png" sizes="32x32">
<link rel="icon" href="https://example.com/wp-content/uploads/favicon-320x320.png" sizes="192x192">
<link rel="apple-touch-icon-precomposed" href="https://example.com/wp-content/uploads/lunarfavicon-320x320.png">
```
Which, as you can see, is not entirely ideal for the setup.

An entire favicon section may be beneficial. As it appears support is needed for Android, Apple, Windows 8+, and of course all browsers.

This [stackoverflow question](https://stackoverflow.com/questions/37653778/which-of-these-icons-are-needed-for-a-website) may also assist in getting more options.

Thanks!

**Comment by Nikeo** [comment]
HI @Tarun80, the theme uses the WP built-in site icon option ( https://make.wordpress.org/core/2015/07/27/site-icon/ ) that you can filter with you custom params.

**Comment by Tarun80** [comment]
I apologize, I was not aware. I have a lot of learning to do still.
