### ISSUE TITLE
[Translation] Add me as translation editor for DE

### ISSUE THREAD

**Issue by jaylinski** [presscustomizr/hueman#349]
Please add me as a translation editor for the language German / Deutsch / de_DE:

https://translate.wordpress.org/locale/de/default/wp-themes/hueman

My handle is [jakobword](https://profiles.wordpress.org/jakobword/).

I'm a native German :de: speaker and added a lot of translations.

Thank you!

**Comment by jaylinski** [comment]
I already got in contact with the german polyglot team.

**Comment by Nikeo** [comment]
Hi @jaylinski !
Sure I've posted the request here : https://make.wordpress.org/polyglots/2016/12/05/de_de-pte-request-for-the/

**Comment by Nikeo** [comment]
Thanks
