### ISSUE TITLE
Illegal string offset

### ISSUE THREAD

**Issue by andornagy** [presscustomizr/hueman#35]
After you save the settings they disappear. I'm using the latest version, hueman-master 

Warning: Illegal string offset 'background-color' in E:\htdocs\wp.andornagy.info\wp-content\themes\hueman\functions\dynamic-styles.php on line 219

Warning: Illegal string offset 'background-image' in E:\htdocs\wp.andornagy.info\wp-content\themes\hueman\functions\dynamic-styles.php on line 220

Warning: Illegal string offset 'background-position' in E:\htdocs\wp.andornagy.info\wp-content\themes\hueman\functions\dynamic-styles.php on line 221

Warning: Illegal string offset 'background-attachment' in E:\htdocs\wp.andornagy.info\wp-content\themes\hueman\functions\dynamic-styles.php on line 222

Warning: Illegal string offset 'background-repeat' in E:\htdocs\wp.andornagy.info\wp-content\themes\hueman\functions\dynamic-styles.php on line 223

Warning: Illegal string offset 'background-size' in E:\htdocs\wp.andornagy.info\wp-content\themes\hueman\functions\dynamic-styles.php on line 224

**Comment by pablopaul** [comment]
I just activated the current master branch and get similar warnings:

![image](https://cloud.githubusercontent.com/assets/635526/12070338/124567e0-b06e-11e5-9ab0-6231a8981241.png)

**Comment by dhm80** [comment]
Yeah, unfortunately there are plenty of "errors". It yould be great if the new developer could use the theme in debug mode and fix the problems.

+1 for that

**Comment by Nikeo** [comment]
Hi,
I've just taken over the development of the theme and will investigate this issue as soon as possible.
Thanks for reporting

**Comment by pablopaul** [comment]
@dhm80 do you see the possibility to concretize 
> plenty of "errors"
?

This would allow @Nikeo and other developers to spend the time on bug fixing instead of search the concrete issue :smile:

**Comment by dhm80** [comment]
@Nikeo Thanks for reopening the ticket and all the best wishes for your new "baby".

@pablopaul Here you go:
```
PHP Notice: Array to string conversion in [...]/wp-content/themes/hueman/functions.php on line 303

PHP Notice: Only variables should be passed by reference in [...]/wp-content/themes/hueman/option-tree/ot-loader.php on line 326

PHP Notice: Only variables should be passed by reference in [...]/wp-content/themes/hueman/option-tree/ot-loader.php on line 98
```

**Comment by Nikeo** [comment]
OK Thanks
