### ISSUE TITLE
Getting Structure Data Issues in Google Webmaster Tools

### ISSUE THREAD

**Issue by QasimYad** [presscustomizr/hueman#355]
Hello Nick! 

I hope you are doing well. I loved your theme and using it when you have started it. 
But after i had upgraded to "hueman_ver_3.2.10" ........ I am getting structure data issue in google webmaster tools. (Note: I am still using this version and not upgraded to 3.2.12 .......)

Nearly 3000 of "hcard" and hentry .......... issues. I have checked the theme's file i have not found any solution or issue in theme's files. 

Any suggestion will be appreciated 
sincerely, 
Qasim

**Comment by Nikeo** [comment]
Hi Qasim!
Can you share your website url ?
Thank

**Comment by QasimYad** [comment]
Hello Nick !
Thanks for your quick response ....... i really appreciate it. 

Here is my website ............  http://www.desktopclass.com/
thanks

**Comment by QasimYad** [comment]
Here is snapshot of error i have ..........
https://i.imgsafe.org/7bba871ae6.jpg

thanks

**Comment by Nikeo** [comment]
OK Thank for sharing this. I'll work on this for the next release

**Comment by QasimYad** [comment]
So nice of you Nick!
Looking forward to see these updates in next release ...........
And ....... thanks for developing such a innovative and intuitive theme...... 
Gratitude
