### ISSUE TITLE
Error on functions.php on childtheme

### ISSUE THREAD

**Issue by dgirona** [presscustomizr/hueman#359]
I have created a child theme. And when I add any function to the new functions.php the page breaks.
I have tried a thousand things and it is not solved. any ideas?

http://blog.perfumesclub.it

Thanks : )

**Comment by jaylinski** [comment]
What breaks? Any error-logs?

**Comment by dgirona** [comment]
White page : (

http://blog.perfumesclub.it

Any Idea?

**Comment by Nikeo** [comment]
Hi @dgirona please start by opening a new support topic in the [Hueman theme forum](https://wordpress.org/support/theme/hueman). We'll see if we need to open an issue for the developers on github or if it's a problem on your side.
Thanks !

**Comment by dgirona** [comment]
AH01071: Got error 'PHP message: PHP Fatal error:  Cannot redeclare ThumbRSS() (previously declared in /usr/home/blogperfumesclub0000/www/wp-content/themes/hueman-child/functions.php:11) in /usr/home/blogperfumesclub0000/www/wp-content/themes/hueman/functions.php on line 27\n', referer: http://blog.perfumesclub.it/wp-admin/themes.php
[Mon Dec 12 08:23:48.489373 2016] [proxy_fcgi:error] [pid 1668] [client 62.81.177.34:52610]

**Comment by dgirona** [comment]
If functions.php are duplicate, in main theme & child theme, functions.php crash.

**Comment by Nikeo** [comment]
yes this is a child theme issue, this won't have to be fixed in the theme then.
I'm closing the issue

**Comment by Nikeo** [comment]
Thanks for the feedback !
