### ISSUE TITLE
Featured Image not uploading after recent update

### ISSUE THREAD

**Issue by ashokkalakoti** [presscustomizr/hueman#362]
Hi Team.
Today i have updated my Huemen Theme for my WordPress blog. after latest update, it's not uploading the featured image. Please suggest me to resolve this issue or kindly guide me to revert back the older release.

Please find the below-attached file for reference.

# SITE_URL:               http://www.techinformant.in
# HOME_URL:               http://www.techinformant.in
# IS MULTISITE :          No

# THEME | VERSION :       Hueman | v3.2.12
# WP VERSION :            4.7

![featured image](https://cloud.githubusercontent.com/assets/24514830/21086062/fac835ca-c03e-11e6-82e8-f48ab18be530.jpg)

**Comment by Nikeo** [comment]
Hi @kashu9999 , your f. images are working fine for me when I connect to your website.
Did you change something since posting the issue ?

**Comment by Tarun80** [comment]
Possibly an issue with a plugin that minifies?
