### ISSUE TITLE
Header image for single post not working on remote server

### ISSUE THREAD

**Issue by menakas** [presscustomizr/hueman#371]
Using Hueman v3.3.2 and Addons v2.0.4, on local server, the header image for single post and no header image for other posts works. But the same does not work on remote server with same version of theme and addons. Image here: [http://imgur.com/a/OD5K9](http://imgur.com/a/OD5K9)

**Comment by menakas** [comment]
Realized that the issue was not due to the new version/changes.

**Comment by Nikeo** [comment]
ouf! :)
