### ISSUE TITLE
Social links cannot be controlled for certain pages

### ISSUE THREAD

**Issue by menakas** [presscustomizr/hueman#373]
With Hueman v3.3.2 and Addons v2.0.4, I tried having social links only on homepage. I tried deleting the links site-wide. But I found that it is not possible. 

Neither can I change the links in home vs. site-wide. 

So, are social links fied across pages?

**Comment by Nikeo** [comment]
I can't reproduce this problem.
I'm able to delete the social links site and set them on home or any other page independently.
Can you try on the test.presscustomizr.com website  and let me know ?
Which browser are you using ?
