### ISSUE TITLE
RTL / Print support

### ISSUE THREAD

**Issue by AlxMedia** [presscustomizr/hueman#38]

**Comment by Bersam** [comment]
Any update on adding this to new release?

**Comment by KHannibal** [comment]
I support this feature request. A print.css file is needed for this theme. :-)

**Comment by dhm80** [comment]
I created a little CSS snippet and put it in my child theme for a nice printing version... Maybe you want to have a look at my post:

https://ansas-meyer.de/programmierung/wordpress/hueman-child-theme-druckversion/

Feel free to use and adapt it as you need ;)

**Comment by Nikeo** [comment]
thanks ! Candidate for next version.

**Comment by KHannibal** [comment]
Thanks @dhm80 I'll try your snippet. :+1: 
@Nikeo what about the direct implementation into the theme, like you said before (for 3.1.7) ? Is it still planned ? :)

**Comment by kapachon** [comment]
Hi! Does Hueman theme has already rtl support?
Thanks!
