### ISSUE TITLE
Add gitlab icon to social links

### ISSUE THREAD

**Issue by ansin218** [presscustomizr/hueman#380]
Are the developers planning to add gitlab icon to the social icons list any time soon? I would love to have a link to my gitlab from the footer and sidebar. In addition, if anyone could tell me any trick to get it add it myself, it would be great. 

Cheers
Ankur

**Comment by jaylinski** [comment]
You can add the GitLab icon here https://github.com/presscustomizr/hueman/blob/dev/assets/czr/js/czr-control.js#L7110 and submit a PR.

Or you can add it yourself in a child theme with `<span class="fa fa-gitlab"></span>`.

This theme is using http://fontawesome.io/.
