### ISSUE TITLE
site title not showing on multisite subsite

### ISSUE THREAD

**Issue by Emmy58** [presscustomizr/hueman#387]
I have a problem with customizing Hueman on multisite. I have a multisite with 3 subsites (in directories, not domains). For every subsite, I have made a child theme.

The first subsite has title ‘TITLE A’ and ‘subtitle A’, both set in the customizer in the Site Identity as site wide option

The second subsite should have ‘TITLE B’ and ‘subtitle B’, both set in the customizer in the Site Identity as site wide option.

The third subsite should have ‘TITLE C’ and no subtitle. Title is set in the customizer in the site identity as side wide option.

As long as I’m in the customizer for subsite B, title B is visible in the showcase, but as soon as I leave the customizer, I only see TITLE A with subtitle B added to it.
In the third case I see title A and no subtitle (an empty subtitle as set for the third subsite).

I hope someone can help on this issue.

**Comment by zipgenius** [comment]
I'm having the same issue.

**Comment by ghost** [comment]
I have this issue as well.

**Comment by ghost** [comment]
Okay I know this is old but I have found that it is only a problem when I have the Hueman Addons plugin installed & activated.  I deactivated it and everything appears fine.  Concern is that I may be missing other featured without the addon.

**Comment by kolaj** [comment]
Same issue here with theme v3.3.25 and addons v2.0.15 (only when the latter are active)

Seems to be an (~1 year) old problem:
https://wordpress.org/support/topic/3-3-website-title-in-subsite-of-a-multisite/
https://wordpress.org/support/topic/multisite-problem-28/
