### ISSUE TITLE
Images inserted as external url link are not parsed properly

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman#394]
https://wordpress.org/support/topic/images-with-posts-not-showing/

Here's how the bug is reported.

> Some pics which are visible in admin preview mode became not visible when published. I am talking about images which are inserted/set as URL link in image options. If it is linked as mediafile it is visible.
> 
> I have a lot of images linked as URL not media 🙁
> 
> The problem is that Hueman theme screens these URL linked images by transparent gif for some strange reason.
> 
> As we found it is written in theme funcs …/wp-admin/theme-editor.php?file=functions%2Fclass-utils.php&theme=hueman
> 
> The function hu_regex_callback must return line with pic or add some parts turned into ‘srcset=’, ‘data-srcset=’ and ‘data-src=’
> 
> Simply adding return $matches[0]; at the begininig helps, but most likely destroys something else in other features.
> 
> Please, let us control this option for some reason or fix it please.
> 
> Otherwise your theme is really awesome! Thanks a lot!
> 
> ps: I can share links in private message

and the next part with a fix proposition

> We found the error.
> 
> It is about lines (images) which are not including spread data "data-src" or for those pics which are set not to use data-smartload. As far as I understand the idea, it should load pics as is.
> 
> Actually, this check up function is not working at all due to odd exclamation mark:
> 
> if ( false !== strpos( $matches[0], 'data-src' ) || preg_match('/ data-smartload *= *"false" */', $matches[0]) )
> 
> We removed the exclamation mark and it is fine now.
> Please fix this error and include it to the next update!

**Comment by Nikeo** [comment]
Hi @eri-trabiccolo I did not test it yet. Can you take _data-src expert_ look on that when you'll get the chance.
thanks

**Comment by eri-trabiccolo** [comment]
:D
(btw I was the _data-srcset expert_ :P , data-src stuff is there from the start, tough I might have changed the checks structure in these years :D )
Well but that check with the exclamation mark says:
"If something else (plugin or we having already parsed that image) added a data-src attribute then do nothing"

Removing the exclamation mark will forbid the php parsing ONLY to those images which do not already that attribute, so the opposite of what we want (in common cases is more or less like disabling the smartload option). 

Have to check better what's the real issue there.
;)

p.s. matches[0] contains the original "string" passed to the preg_callback.
p.p.s
> Please, let us control this option for some reason or fix it please.
Not sure what this means. Isn't the smartload an option?

**Comment by eri-trabiccolo** [comment]
Not able to reproduce the issue.
See the post "Test images linked and smartload" on our test website.

Most likely a conflicting plugin.
