### ISSUE TITLE
Featured post full content loses formatting

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/hueman#395]
Hi,

With reference to this forum thread.
https://wordpress.org/support/topic/featured-post-text-format-issue/

I can replicate this issue.
Go to Appearance -> Customize -> Main Body Design -> Post Lists Design and Content
Under featured posts, Find the setting -> Display the full post content
Enable this option.

Go to front page and you will see the content of the featured post, but there is no top and bottom margin for paragraph. They "stick" together.

Thank you

**Comment by eri-trabiccolo** [comment]
Hi @denzelchia 
doesn't seem a "losing" formatting issue. Formatting is kept to me, it's "just" that the font-size and the paragraphs margin follow a different rule, the one for the posts in the list of posts, and not the one of the single articles.
Do we want to change it?
Should be just about removing the `excerpt` class here:
https://github.com/presscustomizr/hueman/blob/dev/content-featured.php#L30

What do you think guys?
