### ISSUE TITLE
Wrong “landing” places on mobile theme version

### ISSUE THREAD

**Issue by ebretteville** [presscustomizr/hueman#400]
Hye and first of all congratulations for your theme.
I have a little concern. When I load my blog at http://blog.etiennebretteville.com with Firefox for example on my mobile phone, the page is “centered” at the right sidebar widget. Is there a problem on my side or wouldn’t it be great to “land” on the slider or the first article/post?!

Let me know if I can set something or is it an update on your side?!

**Comment by Nikeo** [comment]
Bonjour et merci pour votre retour ! ::)

Ce n'est pas le comportement normal du thème.

Vous avez probablement un conflit de plugin, il y a de nombreuses erreurs javascript sur votre page.
Je peux vous suggérer de désactiver vos plugins afin d'identifier le responsable.

Nous collectons d'abord les problèmes sur le forum utilisateur ( https://wordpress.org/support/theme/hueman )avant d'ouvrir une réelle issue sur Github. Pouvez plutôt poster vos demandes sur le forum ?

Merci !
