### ISSUE TITLE
Dropcap Issue @ homepage

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman#404]
> Hi,
> 
> I'm trying out Hueman theme (free), I like it so far, but....
> 
> if I use the dropcap shortcode for first letter in first paragraph, in the homepage that letter won't show. You can see it on demo, the title post is "An Ode To Earth - Baba Yetu".
> 
> 
> Thank you.

**Comment by ghost** [comment]
Moved in Hueman Addons
