### ISSUE TITLE
sidebars in mobile => allow them to be displayed after the main content

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman#406]
This would fix the problem of sidebars ads being hidden on mobile (reported by user).

**Comment by DALSYM** [comment]
Just wondering if there is an ET for resolving the sidebar issue for Tablets?

**Comment by eri-trabiccolo** [comment]
also requested here:
https://wordpress.org/support/topic/sidebar-ads-on-tablets/

**Comment by ghost** [comment]
To be discussed during our next dev chat
