### ISSUE TITLE
add an easy way to resize the sidebars

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman#411]

**Comment by Nate82** [comment]
This would be great. I was doing it manually by setting my own width and margin-right and adjusting the padding on .col-2cl .main-inner but the latest update with the sticky sidebar messed it all up, I guess it's calculating the width at 340px as you scroll and I had changed the sidebar to 358px so it doesn't work right.

**Comment by fwolfst** [comment]
I'd love to see that feature, too. Note that afaiu it also requires some JS-fiddling (at least it contains the relevant numbers like 340 and a comment about it).
@Nate82 did you succeed to change the sidebar sizes with good results? If so, could you post the required css rules (and maybe JS).

**Comment by Nate82** [comment]
@fwolfst The changes I made worked fine until they changed the sidebar in the recent update. What broke my changes was either the way the sidebar pops out now or the sticky sidebar change they added, my CSS was bugging the sidebar out so I removed my changes. Not sure it's possible anymore to make the sidebar wider with CSS without breaking the sidebar.

**Comment by fwolfst** [comment]
In the Triage-2019 label, when there is no further comment it means kind of 'WONTFIX', does it?

**Comment by ghost** [comment]
Not necessarily.
For the moment a new option for sidebars is not scheduled but it might be re-opened in the future.
