### ISSUE TITLE
RTL Adapt

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman#412]
Implement rtl for the theme

http://www.elmalakrx.com/blog/

**Comment by hosseinfarnia** [comment]
Thank you for implementing rtl Mr Nicolas.

**Comment by eri-trabiccolo** [comment]
requested also here:
https://secure.helpscout.net/conversation/543641655/38971/

**Comment by hosseinfarnia** [comment]
Hi guys,
That would be very very nice of you to fully implement rtl to this theme.
I've been waiting a long time for it to happen.
This theme is very nice with great features and  great support team and I don't want to change it due to the lack of rtl issue.
Thanks

**Comment by hosseinfarnia** [comment]
Hi @Nikeo and @eri-trabiccolo 
I know it takes a lot of time to do it, so I suggest you to implement RTL little by little on each update. That way it is much better and will be finished someday.
