### ISSUE TITLE
Unable to drag resize image inserted into visual editor

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/hueman#415]
Hi,

Please refer to this forum thread.
https://wordpress.org/support/topic/unable-to-rescaleresize-uploaded-images-with-mouse/

I am able to replicate this issue.
The ability to resize image inserted in content editor is gone when using Hueman Theme.
If, I activate WordPress default theme, I am able to drag resize the image.

Please see screen-cast.
http://screencast-o-matic.com/watch/cbejnX6vKi

Thank you

**Comment by Nikeo** [comment]
thanks for reporting @denzelchia. Yes I'm aware of the problem, it has been reported in the latest release comments as weel.
I've started to analyze the problem but I don't really have a clear diagnostic now.

**Comment by eri-trabiccolo** [comment]
https://github.com/presscustomizr/hueman/blob/v3.3.6/functions/init-admin.php#L517
Typo: Semicolon after the closing brace "breaks" the css
