### ISSUE TITLE
Improve Hx structure consistency accross all pages / SEO / font-size /...

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman#420]
> Page Title not appearing as H1 tag, H2 tag is small and H3 tag is huge.
> 
> Ok when I use the front page the h1 tag is the text where the logo should be (site title). The H2 tags are smaller and the H3 tags are larger. If you want to see please take a look at http://plasmacutterpro.
> 
> The page title appears as an H2 tag. I thought for proper SEO, the page title should be an H1 and the major content headings should be H2 tags. Is that correct?
> 
> Now if I go to any other interior page, there is no H1 tag and the page title is an H2 tag. To look at this, please visit any internal page such as http://plasmacutterpro.com/hobart-500564-airforce-12i-plasma-cutter-review/ and view the source. Site title does not have an H1 tag as expected but the Page Title is an H2 tag but I would expect it to be an H1 tag.
> 
> Is this making sense?
> 
> I don't have any custom CSS and am just using the base theme. I have an insert headers and footers plugin and use Table Press with some custom CSS to override some of their classes but otherwise, pretty basic setup and nothing else that would modify CSS code.
> 
> Thoughts?

**Comment by gonzogr8** [comment]
see also #366

**Comment by ghost** [comment]
fixed in  954ee03
