### ISSUE TITLE
Theme Shaking 

### ISSUE THREAD

**Issue by codeslane** [presscustomizr/hueman#426]
New Update is shaking on desktop mode in each and every 2 seconds.

**Comment by Nikeo** [comment]
Can you share an url or a screencast of the problem ?

**Comment by codeslane** [comment]
https://www.codeslane.com this is my site URL. 
The problem is in footer area only stay for 2 mins. watch and feel the issue.

**Comment by Nikeo** [comment]
Which browser are you using ?
Can you reproduce the problem on the [hueman theme demo](http://demo-hueman.presscustomizr.com/) site ?

**Comment by Nikeo** [comment]
I did not experienced any issue. Which browser are you using ?
Can you reproduce the problem on the [hueman theme demo](http://demo-hueman.presscustomizr.com/) site ?
Thanks

**Comment by codeslane** [comment]
@Nikeo I'm using update google chrome. I'm having no issue on demo maybe because of the full boxed layout.

Also the [hightlight]example[/hightlight] isn't working.  Check the article ending.
![screenshot 77](https://cloud.githubusercontent.com/assets/26877201/24717759/2cf119e2-1a51-11e7-9f71-ae14cd516fff.png)


SS attached 
Thanks.

**Comment by eri-trabiccolo** [comment]
Hi @codeslane 
about the highlight shortcode, for what I can see there's a typo in your text.
You opened the shortcode with [hightlight] while it must be [highlight]. ;)
Hope this helps.

**Comment by codeslane** [comment]
@eri-trabiccolo thanks a sir.
