### ISSUE TITLE
Mobile Header Menu Closes Too Early [bug] 

### ISSUE THREAD

**Issue by codeslane** [presscustomizr/hueman#433]
@Nikeo @eri-trabiccolo Sir, 

In Mobile Header Menu if the Menus are long and try to scroll the backend of theme selects and while moving the menu and instead of menu theme movies and closes sometimes. 
Mostly issues is when the menu floats in between the articles or page and in transparent mode. Long List of Menus isn't working smoothly. 

I tired several troubleshooting and also deactivations or plugins but nothing works. 
As this thing might be a bug in theme. 
Please look over this. 

#bug #urgent 

Regards 
- Vaibhav Singh
(Software Developer)

**Comment by codeslane** [comment]
@Nikeo @eri-trabiccolo Getting and Facing the same issue in Demo-Hueman.

**Comment by Nikeo** [comment]
Hi  @codeslane yes I already noticed this problem and was actually searching for the best solution to fix it.
Thanks for reporting the problem. I'm on it.

**Comment by codeslane** [comment]
@Nikeo I think transparency causing the issue. 
Decrease the transparency a bit and blur the navigation menu sheet. 
Check the CSS that might solve this problem. 

Thanks.

**Comment by codeslane** [comment]
Issue have been resolved with new update. 
thanks for working on it.
