### ISSUE TITLE
FEATURE REQUEST: All Google Fonts instead of a few

### ISSUE THREAD

**Issue by nilsbyte** [presscustomizr/hueman#60]
Hello! Nice theme, the best free one i have found so far.

I posted this request on the wordpress.org support forum but some random dude showed up to pull his finger in my face and writing about wp.org theme guidelines...

Can you add the functionality to choose from all available Google Fonts instead of just a few? That would give the users much more flexiblity.

As an extension of this request, it would be nice to let the user choose font colors and sizes for individual elements.

hope for your feedback!

**Comment by keunes** [comment]
+1 for choosing fonts for different elements (e.g. blog title vs post/page title vs contents)

**Comment by elliot-labs** [comment]
I would say that would be a good setting for the styling part of Options
Tree.

+1 for sub idea

On Sun, Mar 1, 2015 at 10:20 AM, keunes <notifications@github.com> wrote:

> +1 for choosing fonts for different elements (e.g. blog title vs post/page
> title vs contents)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AlxMedia/hueman/issues/60#issuecomment-76601095>.
>



-- 

Elliot

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.

**Comment by Leeo97one** [comment]
It should not be that complicate the theme options too...

**Comment by elliot-labs** [comment]
I agree: too many options in the style section could get confusing.

Maybe there could be a new section for fonts? It could be combined with
something else so it is not just sitting there by itself...

On Sun, Mar 1, 2015 at 10:55 AM, Léo Pellet <notifications@github.com>
wrote:

> It should not be that complicate the theme options too...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AlxMedia/hueman/issues/60#issuecomment-76603580>.
>



-- 

Elliot

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.
