### ISSUE TITLE
The tracking code has to be in the head

### ISSUE THREAD

**Issue by agatha65** [presscustomizr/hueman#93]
In functions.php
change
add_filter( 'wp_footer', 'alx_tracking_code' );
to
add_filter( 'wp_head', 'alx_tracking_code' );

**Comment by elliot-labs** [comment]
Is this for tracking Hueman usage? or is this GA tracking?

**Comment by agatha65** [comment]
this is especially for GA. I found this problem when trying to verify web master  tools account with analytics account. The message was something like  your code is not at right place.

**Comment by elliot-labs** [comment]
I use the Yost plugin and it works great... Do you enter it manually?

**Comment by agatha65** [comment]
It is important here to make this great theme better.
I don't have problems to fix it in the theme and yes sometimes I use the same plugin or similar so in these cases I have a choice.

**Comment by elliot-labs** [comment]
If there is a real difference in the theme then I would also like to have it fixed :+1:.
Personally with my setup don't have an issue...

**Comment by keunes** [comment]
Thanks @agatha65 for sharing :+1: 
Would make things for site owners just a tiny wee easier
