### ISSUE TITLE
FEATURE REQUEST: Custom sidebar titles

### ISSUE THREAD

**Issue by keunes** [presscustomizr/hueman#98]
I wanted to display a stream of tweets in the sidebar on the homepage, but then the 'more' sidebar title seemed a little odd. I therefore adapted sidebar-2.php (inserted `<?php if ( is_front_page() && is_home() ) { _e('My latest tweets','hueman');} else { _e('More','hueman');} ?>`) to make a different title appear on the homepage.
It would be a great feature if the theme would use add a variable for each sidebar, so that the following options are available for each sidebar:
- Title (make this appear in the front-end of the site, i.e. where now is 'more')
- Name (make this appear in the back-end of the site)
- Sidebar ID (well, as its necessary. Although it would be extra nice if it were automatically based on 'name')

This way, if there's only one widget in a sidebar, the title can be removed from the widget and placed in the sidebar title, making it visually more appealing.

![before](https://cloud.githubusercontent.com/assets/11229646/6431393/495afd66-c02e-11e4-868f-b31efd79108b.png) ![after](https://cloud.githubusercontent.com/assets/11229646/6431392/495ab7ca-c02e-11e4-9432-4c25dc77bffb.png)

**Comment by jaylinski** [comment]
+1
had to make a child theme for this.

**Comment by elliot-labs** [comment]
+1

**Comment by keunes** [comment]
@jaylinski, how did you tackle the issue? I made a child theme as well, but not sure if my method is the smartest way to do so (see code of original post).

**Comment by jaylinski** [comment]
@keunes I added edited versions of the hueman language files to my child-theme. I simply replaced the translations for the two sidebar headings. but obviously your solution is better (and more flexible).

**Comment by ilkerceng** [comment]
@keunes is there any progress on this? we also need to customize the title, thanks.

**Comment by keunes** [comment]
@ilkerceng Well, I made a feature request on somebody else's software, so I don't know if there's any progress :P But from the looks of it, I'd guess not.

**Comment by ilkerceng** [comment]
@keunes i have accidentally tagged you :)) it should have been @Nikeo
